-- ============================================================
-- SQL PRACTICE - 05_WINDOW_FUNCTIONS (SOLUTIONS)
-- ============================================================
-- database: practice.db (SQLite)
-- ============================================================

-- Q1: Assign a unique sequential integer starting from 1 to each employee sorted by salary descending (use ROW_NUMBER()).
SELECT first_name, last_name, salary,
       ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num
FROM employees;

-- Q2: Rank all employees by salary from highest to lowest. If salaries match, assign the same rank and skip ranks (use RANK()).
SELECT first_name, last_name, salary,
       RANK() OVER (ORDER BY salary DESC) AS rnk
FROM employees;

-- Q3: Rank all employees by salary from highest to lowest. If salaries match, assign same rank without skipping (use DENSE_RANK()).
SELECT first_name, last_name, salary,
       DENSE_RANK() OVER (ORDER BY salary DESC) AS dense_rnk
FROM employees;

-- Q4: Rank products by price descending within each category using ROW_NUMBER().
SELECT name, category, price,
       ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) AS category_row_num
FROM products;

-- Q5: Rank products by price descending within each category using DENSE_RANK().
SELECT name, category, price,
       DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) AS category_dense_rank
FROM products;

-- Q6: Assign a row number to orders placed by each customer, sorted by order_date ascending.
SELECT id AS order_id, customer_id, order_date, total_amount,
       ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date ASC) AS customer_order_seq
FROM orders;

-- Q7: Rank orders by total_amount descending within each order status.
SELECT id AS order_id, status, total_amount,
       RANK() OVER (PARTITION BY status ORDER BY total_amount DESC) AS status_amount_rank
FROM orders;

-- Q8: Rank customers by signup_date ascending within their respective countries.
SELECT first_name, last_name, country, signup_date,
       ROW_NUMBER() OVER (PARTITION BY country ORDER BY signup_date ASC) AS signup_rank
FROM customers;

-- Q9: Select employee first name, last name, salary, and the salary of the next highest paid employee (use LEAD()).
SELECT first_name, last_name, salary,
       LEAD(salary, 1) OVER (ORDER BY salary ASC) AS next_higher_salary
FROM employees;

-- Q10: Select employee first name, last name, salary, and the salary of the previous highest paid employee (use LAG()).
SELECT first_name, last_name, salary,
       LAG(salary, 1) OVER (ORDER BY salary ASC) AS prev_lower_salary
FROM employees;

-- Q11: Select employee first name, last name, salary, and the salary of the next hire in their department (LEAD by hire_date).
SELECT first_name, last_name, salary, department_id, hire_date,
       LEAD(salary, 1) OVER (PARTITION BY department_id ORDER BY hire_date ASC) AS next_hire_salary
FROM employees;

-- Q12: Select order_id, customer_id, total_amount, order_date, and the total_amount of the customer's previous order (LAG).
SELECT id AS order_id, customer_id, total_amount, order_date,
       LAG(total_amount, 1) OVER (PARTITION BY customer_id ORDER BY order_date ASC) AS prev_order_amount
FROM orders;

-- Q13: Select product name, price, category, and the price of the cheapest product in the same category (use FIRST_VALUE()).
SELECT name, price, category,
       FIRST_VALUE(price) OVER (PARTITION BY category ORDER BY price ASC) AS cheapest_category_price
FROM products;

-- Q14: Select product name, price, category, and the price of the most expensive product in the same category (use FIRST_VALUE/LAST_VALUE).
SELECT name, price, category,
       FIRST_VALUE(price) OVER (PARTITION BY category ORDER BY price DESC) AS expensive_category_price
FROM products;

-- Q15: Calculate the running total of employee salaries, ordered by hire_date ascending.
SELECT first_name, last_name, salary, hire_date,
       SUM(salary) OVER (ORDER BY hire_date ASC) AS running_salary_total
FROM employees;

-- Q16: Calculate the running total of order revenues, ordered by order_date ascending.
SELECT id AS order_id, order_date, total_amount,
       SUM(total_amount) OVER (ORDER BY order_date ASC) AS cumulative_revenue
FROM orders;

-- Q17: Calculate the running total of revenue generated by each customer individually, ordered by order_date ascending.
SELECT id AS order_id, customer_id, order_date, total_amount,
       SUM(total_amount) OVER (PARTITION BY customer_id ORDER BY order_date ASC) AS customer_cumulative_spent
FROM orders;

-- Q18: Calculate the cumulative quantity of products sold in order_items, ordered by order_id ascending.
SELECT id, order_id, product_id, quantity,
       SUM(quantity) OVER (ORDER BY order_id ASC) AS cumulative_units_sold
FROM order_items;

-- Q19: Calculate the 3-order moving average of total_amount for orders (use ROWS BETWEEN 2 PRECEDING AND CURRENT ROW).
SELECT id AS order_id, order_date, total_amount,
       AVG(total_amount) OVER (ORDER BY order_date ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg_3_orders
FROM orders;

-- Q20: Calculate the 2-employee moving average of salary in hire_date order.
SELECT first_name, last_name, salary, hire_date,
       AVG(salary) OVER (ORDER BY hire_date ASC ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS moving_avg_2_employees
FROM employees;

-- Q21: Divide all products into 4 price quartiles (use NTILE(4)).
SELECT name, price, NTILE(4) OVER (ORDER BY price ASC) AS price_quartile FROM products;

-- Q22: Divide all employees into 3 salary tiers (NTILE(3)).
SELECT first_name, last_name, salary, NTILE(3) OVER (ORDER BY salary ASC) AS salary_tier FROM employees;

-- Q23: Select employee name, salary, and the percentage of their department's total salary expense their salary represents.
SELECT first_name, last_name, salary, department_id,
       (salary / SUM(salary) OVER (PARTITION BY department_id)) * 100.0 AS salary_percentage_in_dept
FROM employees;

-- Q24: Select product name, price, category, and the difference between its price and the category's average price.
SELECT name, price, category,
       price - AVG(price) OVER (PARTITION BY category) AS diff_from_category_avg
FROM products;

-- Q25: Find the maximum salary in each department and display it on every employee's row (use MAX() as a window function).
SELECT first_name, last_name, salary, department_id,
       MAX(salary) OVER (PARTITION BY department_id) AS max_dept_salary
FROM employees;

-- Q26: Find the average salary in each department and display it on every employee's row (use AVG() as a window function).
SELECT first_name, last_name, salary, department_id,
       AVG(salary) OVER (PARTITION BY department_id) AS avg_dept_salary
FROM employees;

-- Q27: Count the number of employees in each department, showing the count on every employee row (use COUNT() as window).
SELECT first_name, last_name, department_id,
       COUNT(*) OVER (PARTITION BY department_id) AS dept_employee_count
FROM employees;

-- Q28: Select customer name, country, and the signup date of the first customer who signed up in that country (use FIRST_VALUE).
SELECT first_name, last_name, country, signup_date,
       FIRST_VALUE(signup_date) OVER (PARTITION BY country ORDER BY signup_date ASC) AS first_signup_in_country
FROM customers;

-- Q29: Find the difference in order amount between each order and the average order amount (using AVG() window function).
SELECT id AS order_id, total_amount,
       total_amount - AVG(total_amount) OVER () AS diff_from_global_avg
FROM orders;

-- Q30: Select customer name, order date, total amount, and the percentage growth in order amount from their previous order.
WITH OrderLag AS (
    SELECT id AS order_id, customer_id, order_date, total_amount,
           LAG(total_amount, 1) OVER (PARTITION BY customer_id ORDER BY order_date ASC) AS prev_amount
    FROM orders
)
SELECT o.order_id, c.first_name || ' ' || c.last_name AS customer_name, o.order_date, o.total_amount, o.prev_amount,
       CASE 
           WHEN o.prev_amount IS NULL THEN NULL
           ELSE ((o.total_amount - o.prev_amount) / o.prev_amount) * 100.0
       END AS growth_percentage
FROM OrderLag o
INNER JOIN customers c ON o.customer_id = c.id;

-- Q31: Select employee name, salary, and their ranking within their department (using DENSE_RANK()).
SELECT first_name || ' ' || e.last_name AS employee_name, salary, department_id,
       DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS dept_rank
FROM employees e;

-- Q32: Select employee name, hire_date, and the hire_date of the person hired exactly before them in the company.
SELECT first_name || ' ' || last_name AS employee_name, hire_date,
       LAG(hire_date, 1) OVER (ORDER BY hire_date ASC) AS prev_hire_date
FROM employees;

-- Q33: Select product name, price, and the price of the next most expensive product in the catalog.
SELECT name, price,
       LEAD(price, 1) OVER (ORDER BY price ASC) AS next_expensive_price
FROM products;

-- Q34: Select order_id, customer_id, order_date, total_amount, and the moving total of the last 3 orders (including current).
SELECT id AS order_id, customer_id, order_date, total_amount,
       SUM(total_amount) OVER (PARTITION BY customer_id ORDER BY order_date ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_total_3
FROM orders;

-- Q35: Select product name, category, price, and the average price of the category (using AVG() window function).
SELECT name, category, price,
       AVG(price) OVER (PARTITION BY category) AS avg_cat_price
FROM products;

-- Q36: Find the difference in price between each product and the next cheapest product in the same category.
WITH SortedProducts AS (
    SELECT name, category, price,
           LAG(price, 1) OVER (PARTITION BY category ORDER BY price ASC) AS prev_price
    FROM products
)
SELECT name, category, price, prev_price,
       CASE WHEN prev_price IS NULL THEN NULL ELSE price - prev_price END AS price_diff
FROM SortedProducts;

-- Q37: Select employee name, salary, and the difference between their salary and the highest salary in their department.
SELECT first_name || ' ' || last_name AS employee_name, salary, department_id,
       MAX(salary) OVER (PARTITION BY department_id) - salary AS salary_gap
FROM employees;

-- Q38: Select customer name, signup date, and the signup date of the customer who signed up immediately after them.
SELECT first_name || ' ' || last_name AS customer_name, signup_date,
       LEAD(signup_date, 1) OVER (ORDER BY signup_date ASC) AS next_signup_date
FROM customers;

-- Q39: Select order_id, order_date, total_amount, and the average order amount of all orders placed on or before that date.
SELECT id AS order_id, order_date, total_amount,
       AVG(total_amount) OVER (ORDER BY order_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_avg
FROM orders;

-- Q40: Select employee name, department name, salary, and the sum of salaries of all employees hired after them in the same department.
SELECT e.first_name || ' ' || e.last_name AS employee_name, d.name AS department_name, e.salary, e.hire_date,
       SUM(e.salary) OVER (PARTITION BY e.department_id ORDER BY e.hire_date ASC ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS salaries_following
FROM employees e
INNER JOIN departments d ON e.department_id = d.id;

-- Q41: Rank departments by their total salary expense using DENSE_RANK() (requires aggregation + window function).
SELECT department_id, SUM(salary) AS total_salaries,
       DENSE_RANK() OVER (ORDER BY SUM(salary) DESC) AS salary_expense_rank
FROM employees
GROUP BY department_id;

-- Q42: Rank customers by their total spending descending using RANK() (requires aggregation + window function).
SELECT customer_id, SUM(total_amount) AS total_spent,
       RANK() OVER (ORDER BY SUM(total_amount) DESC) AS spending_rank
FROM orders
GROUP BY customer_id;

-- Q43: Rank product categories by total quantity sold descending using ROW_NUMBER().
SELECT p.category, SUM(oi.quantity) AS total_sold,
       ROW_NUMBER() OVER (ORDER BY SUM(oi.quantity) DESC) AS rank
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.id
GROUP BY p.category;

-- Q44: Select product name, price, and its rank from cheapest to most expensive (using RANK()).
SELECT name, price, RANK() OVER (ORDER BY price ASC) AS cheapest_rank FROM products;

-- Q45: Select employee name, salary, and the salary of the 3rd highest paid employee in their department (use LEAD/LAG or window).
WITH RankedEmployees AS (
    SELECT first_name, last_name, salary, department_id,
           DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS sal_rank
    FROM employees
)
SELECT re.*, 
       (SELECT DISTINCT salary FROM RankedEmployees WHERE department_id = re.department_id AND sal_rank = 3) AS salary_3rd_highest
FROM RankedEmployees re;

-- Q46: Find the rolling 7-day total revenue (assuming daily data, otherwise last 7 orders moving total).
SELECT id AS order_id, order_date, total_amount,
       SUM(total_amount) OVER (ORDER BY order_date ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_total_7_orders
FROM orders;

-- Q47: Select customer name, country, signup date, and their rank within their country (using DENSE_RANK()).
SELECT first_name || ' ' || last_name AS customer_name, country, signup_date,
       DENSE_RANK() OVER (PARTITION BY country ORDER BY signup_date ASC) AS country_signup_rank
FROM customers;

-- Q48: Select product name, category, price, and the price of the 2nd most expensive product in that category.
WITH RankedProducts AS (
    SELECT name, category, price,
           DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) AS price_rank
    FROM products
)
SELECT rp.name, rp.category, rp.price,
       (SELECT DISTINCT price FROM RankedProducts WHERE category = rp.category AND price_rank = 2) AS second_expensive_price
FROM RankedProducts rp;

-- Q49: Select employee name, salary, and the percentage their salary represents of the company's total salary budget.
SELECT first_name || ' ' || last_name AS employee_name, salary,
       (salary / SUM(salary) OVER ()) * 100.0 AS budget_percentage
FROM employees;

-- Q50: Select order_id, customer_id, total_amount, and the running average of order amounts for that customer.
SELECT id AS order_id, customer_id, total_amount, order_date,
       AVG(total_amount) OVER (PARTITION BY customer_id ORDER BY order_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_avg
FROM orders;

-- Q51: Find the employee earning the highest salary in each department using DENSE_RANK() in a subquery/CTE.
WITH RankedEmployees AS (
    SELECT *, DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rank
    FROM employees
)
SELECT * FROM RankedEmployees WHERE rank = 1;

-- Q52: Find the 3 most expensive products in each category using ROW_NUMBER() in a subquery/CTE.
WITH RankedProducts AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) AS row_num
    FROM products
)
SELECT * FROM RankedProducts WHERE row_num <= 3;

-- Q53: Find the customer who placed the largest order in each country using RANK().
WITH CountryOrders AS (
    SELECT o.id AS order_id, o.total_amount, c.first_name, c.last_name, c.country,
           RANK() OVER (PARTITION BY c.country ORDER BY o.total_amount DESC) AS rnk
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.id
)
SELECT * FROM CountryOrders WHERE rnk = 1;

-- Q54: Find the employee who has the longest tenure in each department using ROW_NUMBER().
WITH TenuredEmployees AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY hire_date ASC) AS row_num
    FROM employees
)
SELECT * FROM TenuredEmployees WHERE row_num = 1;

-- Q55: Select the order details for the first order placed by each customer using DENSE_RANK().
WITH FirstOrders AS (
    SELECT *, DENSE_RANK() OVER (PARTITION BY customer_id ORDER BY order_date ASC, id ASC) AS rnk
    FROM orders
)
SELECT * FROM FirstOrders WHERE rnk = 1;

-- Q56: Find the second cheapest product in each category using a window function.
WITH RankedProducts AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY price ASC) AS row_num
    FROM products
)
SELECT * FROM RankedProducts WHERE row_num = 2;

-- Q57: Find the employee who was hired immediately after Bob Jones using a window function.
WITH HiredOrder AS (
    SELECT *, LEAD(first_name || ' ' || last_name, 1) OVER (ORDER BY hire_date ASC) AS next_hired
    FROM employees
)
SELECT * FROM HiredOrder WHERE first_name = 'Bob' AND last_name = 'Jones';

-- Q58: Find products whose price is within the top 20% of prices in their category (use NTILE(5)).
WITH CategoryQuartiles AS (
    SELECT *, NTILE(5) OVER (PARTITION BY category ORDER BY price DESC) AS price_bracket
    FROM products
)
SELECT * FROM CategoryQuartiles WHERE price_bracket = 1;

-- Q59: Find customers whose total spending is in the top 25% of all customer spending.
WITH CustomerSpending AS (
    SELECT customer_id, SUM(total_amount) AS spent,
           NTILE(4) OVER (ORDER BY SUM(total_amount) DESC) AS quartile
    FROM orders
    GROUP BY customer_id
)
SELECT cs.customer_id, c.first_name, c.last_name, cs.spent
FROM CustomerSpending cs
INNER JOIN customers c ON cs.customer_id = c.id
WHERE cs.quartile = 1;

-- Q60: Find the department that has the highest average salary using a window function.
WITH DeptAvgSalary AS (
    SELECT department_id, AVG(salary) AS avg_sal,
           ROW_NUMBER() OVER (ORDER BY AVG(salary) DESC) AS rank
    FROM employees
    GROUP BY department_id
)
SELECT das.department_id, d.name, das.avg_sal
FROM DeptAvgSalary das
INNER JOIN departments d ON das.department_id = d.id
WHERE das.rank = 1;

-- Q61: Select employee name, department, hire date, and the days elapsed since the previous hire in the same department.
-- Note: SQLite does not have direct DATEDIFF. We can cast date string to julianday to get difference in days.
WITH HiredLag AS (
    SELECT first_name, last_name, department_id, hire_date,
           LAG(hire_date, 1) OVER (PARTITION BY department_id ORDER BY hire_date ASC) AS prev_hire
    FROM employees
)
SELECT first_name, last_name, department_id, hire_date, prev_hire,
       CASE 
           WHEN prev_hire IS NULL THEN NULL 
           ELSE CAST(julianday(hire_date) - julianday(prev_hire) AS INT) 
       END AS days_elapsed
FROM HiredLag;

-- Q62: Select order_id, customer_id, order_date, and the elapsed days since the customer's previous order.
WITH OrderLag AS (
    SELECT id AS order_id, customer_id, order_date,
           LAG(order_date, 1) OVER (PARTITION BY customer_id ORDER BY order_date ASC) AS prev_order
    FROM orders
)
SELECT order_id, customer_id, order_date, prev_order,
       CASE 
           WHEN prev_order IS NULL THEN NULL 
           ELSE CAST(julianday(order_date) - julianday(prev_order) AS INT) 
       END AS days_between_orders
FROM OrderLag;

-- Q63: Calculate the running sum of orders count by date (cumulative orders count).
SELECT order_date, COUNT(*) AS daily_orders,
       SUM(COUNT(*)) OVER (ORDER BY order_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_orders
FROM orders
GROUP BY order_date;

-- Q64: Select employee name, salary, and the cumulative average salary of employees hired on or before them.
SELECT first_name || ' ' || last_name AS employee_name, salary, hire_date,
       AVG(salary) OVER (ORDER BY hire_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_avg_salary
FROM employees;

-- Q65: Select product name, price, category, and the cumulative maximum price in that category, ordered by price ascending.
SELECT name, category, price,
       MAX(price) OVER (PARTITION BY category ORDER BY price ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_max_price
FROM products;

-- Q66: Select customer name, country, signup date, and the cumulative count of customers registered in that country.
SELECT first_name || ' ' || last_name AS customer_name, country, signup_date,
       COUNT(*) OVER (PARTITION BY country ORDER BY signup_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_signup_count
FROM customers;

-- Q67: Select employee name, salary, and the difference between their salary and the average salary of the entire company.
SELECT first_name || ' ' || last_name AS employee_name, salary,
       salary - AVG(salary) OVER () AS diff_from_company_avg
FROM employees;

-- Q68: Select order_id, order_date, total_amount, and the difference between it and the next order's total_amount.
WITH OrderLead AS (
    SELECT id AS order_id, order_date, total_amount,
           LEAD(total_amount, 1) OVER (ORDER BY order_date ASC, id ASC) AS next_amount
    FROM orders
)
SELECT order_id, order_date, total_amount, next_amount,
       CASE WHEN next_amount IS NULL THEN NULL ELSE total_amount - next_amount END AS amount_diff
FROM OrderLead;

-- Q69: Select product name, category, price, and the difference in price compared to the next cheapest product in the catalog.
WITH ProductLead AS (
    SELECT name, category, price,
           LEAD(price, 1) OVER (ORDER BY price ASC) AS next_higher_price
    FROM products
)
SELECT name, category, price, next_higher_price,
       CASE WHEN next_higher_price IS NULL THEN NULL ELSE next_higher_price - price END AS price_diff
FROM ProductLead;

-- Q70: Select customer name, country, and the difference in signup date (days) compared to the first customer in the same country.
WITH CustomerFirst AS (
    SELECT first_name, last_name, country, signup_date,
           FIRST_VALUE(signup_date) OVER (PARTITION BY country ORDER BY signup_date ASC) AS first_signup
    FROM customers
)
SELECT first_name, last_name, country, signup_date, first_signup,
       CAST(julianday(signup_date) - julianday(first_signup) AS INT) AS days_since_first_signup
FROM CustomerFirst;

-- Q71: Rank customers by total spending, and count how many customers have the exact same rank.
WITH CustomerRanks AS (
    SELECT customer_id, SUM(total_amount) AS spent,
           RANK() OVER (ORDER BY SUM(total_amount) DESC) AS rnk
    FROM orders
    GROUP BY customer_id
)
SELECT rnk, COUNT(*) AS customers_with_rank FROM CustomerRanks GROUP BY rnk;

-- Q72: Find the product category with the highest total units sold, and show its rank compared to other categories.
WITH CategoryVolume AS (
    SELECT p.category, SUM(oi.quantity) AS total_sold,
           RANK() OVER (ORDER BY SUM(oi.quantity) DESC) AS rank
    FROM order_items oi
    INNER JOIN products p ON oi.product_id = p.id
    GROUP BY p.category
)
SELECT * FROM CategoryVolume WHERE rank = 1;

-- Q73: Select employee name, department name, salary, and the rank of their department based on average salary.
WITH DeptRanks AS (
    SELECT department_id, AVG(salary) AS avg_sal,
           DENSE_RANK() OVER (ORDER BY AVG(salary) DESC) AS dept_rank
    FROM employees
    GROUP BY department_id
)
SELECT e.first_name || ' ' || e.last_name AS employee_name, d.name AS department_name, e.salary, dr.dept_rank
FROM employees e
INNER JOIN departments d ON e.department_id = d.id
INNER JOIN DeptRanks dr ON e.department_id = dr.department_id;

-- Q74: Select customer country, total spending in that country, and the rank of that country based on total spending.
WITH CountrySpending AS (
    SELECT c.country, SUM(o.total_amount) AS total_spent,
           RANK() OVER (ORDER BY SUM(o.total_amount) DESC) AS country_rank
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.id
    GROUP BY c.country
)
SELECT * FROM CountrySpending;

-- Q75: Select product name, stock, category, and the rank of the product based on stock level within its category.
SELECT name, category, stock,
       RANK() OVER (PARTITION BY category ORDER BY stock DESC) AS stock_rank
FROM products;

-- Q76: Find the employee with the lowest salary in each department using DENSE_RANK() in a CTE.
WITH RankedSalary AS (
    SELECT *, DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary ASC) AS rnk
    FROM employees
)
SELECT * FROM RankedSalary WHERE rnk = 1;

-- Q77: Find the product with the lowest stock level in each category using ROW_NUMBER() in a CTE.
WITH RankedStock AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY stock ASC) AS row_num
    FROM products
)
SELECT * FROM RankedStock WHERE row_num = 1;

-- Q78: Find the customer who registered first in each country using a window function.
WITH RankedSignups AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY country ORDER BY signup_date ASC) AS row_num
    FROM customers
)
SELECT * FROM RankedSignups WHERE row_num = 1;

-- Q79: Find the order with the lowest total amount for each customer using a window function.
WITH CustomerMinOrder AS (
    SELECT *, RANK() OVER (PARTITION BY customer_id ORDER BY total_amount ASC) AS rnk
    FROM orders
)
SELECT * FROM CustomerMinOrder WHERE rnk = 1;

-- Q80: Find the product category with the highest total stock level, showing its rank.
WITH CategoryStock AS (
    SELECT category, SUM(stock) AS total_stock,
           RANK() OVER (ORDER BY SUM(stock) DESC) AS rank
    FROM products
    GROUP BY category
)
SELECT * FROM CategoryStock;

-- Q81: Calculate the running total of quantities sold for each product_id individually.
SELECT id, order_id, product_id, quantity,
       SUM(quantity) OVER (PARTITION BY product_id ORDER BY order_id ASC) AS running_quantity_sold
FROM order_items;

-- Q82: Calculate the running average of unit prices in order_items.
SELECT id, order_id, product_id, unit_price,
       AVG(unit_price) OVER (ORDER BY order_id ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_avg_unit_price
FROM order_items;

-- Q83: Calculate the cumulative sum of budgets for departments located in "New York".
SELECT id, name, budget, location,
       SUM(budget) OVER (ORDER BY id ASC) AS cumulative_budget
FROM departments
WHERE location = 'New York';

-- Q84: Calculate the cumulative average of budgets for departments located in "San Francisco".
SELECT id, name, budget, location,
       AVG(budget) OVER (ORDER BY id ASC) AS cumulative_avg_budget
FROM departments
WHERE location = 'San Francisco';

-- Q85: Select employee name, salary, hire date, and the running count of hires in the company.
SELECT first_name || ' ' || last_name AS employee_name, salary, hire_date,
       COUNT(*) OVER (ORDER BY hire_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_hires_count
FROM employees;

-- Q86: Select customer name, signup date, and the running count of customers signed up.
SELECT first_name || ' ' || last_name AS customer_name, signup_date,
       COUNT(*) OVER (ORDER BY signup_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_signup_count
FROM customers;

-- Q87: Select product name, price, category, and the running average price of products in the same category.
SELECT name, price, category,
       AVG(price) OVER (PARTITION BY category ORDER BY price ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_category_avg
FROM products;

-- Q88: Select order_id, order_date, total_amount, and the running maximum total_amount.
SELECT id AS order_id, order_date, total_amount,
       MAX(total_amount) OVER (ORDER BY order_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_max_amount
FROM orders;

-- Q89: Select employee name, salary, and the running minimum salary in their department.
SELECT first_name || ' ' || last_name AS employee_name, salary, department_id,
       MIN(salary) OVER (PARTITION BY department_id ORDER BY hire_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_min_dept_salary
FROM employees;

-- Q90: Select customer name, country, and the running maximum order total placed by them.
SELECT o.id AS order_id, c.first_name || ' ' || c.last_name AS customer_name, c.country, o.total_amount,
       MAX(o.total_amount) OVER (PARTITION BY o.customer_id ORDER BY o.order_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_max_order_amount
FROM orders o
INNER JOIN customers c ON o.customer_id = c.id;

-- Q91: Find the employee who was hired second in each department.
WITH HiredSequence AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY hire_date ASC) AS row_num
    FROM employees
)
SELECT * FROM HiredSequence WHERE row_num = 2;

-- Q92: Find the product that is the second most expensive in each category.
WITH PriceSequence AS (
    SELECT *, DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) AS rnk
    FROM products
)
SELECT * FROM PriceSequence WHERE rnk = 2;

-- Q93: Find the customer who placed the second largest order.
WITH SpendSequence AS (
    SELECT *, RANK() OVER (ORDER BY total_amount DESC) AS rnk
    FROM orders
)
SELECT * FROM SpendSequence WHERE rnk = 2;

-- Q94: Find the order with the second highest total amount for each customer.
WITH CustomerOrders AS (
    SELECT *, RANK() OVER (PARTITION BY customer_id ORDER BY total_amount DESC) AS rnk
    FROM orders
)
SELECT * FROM CustomerOrders WHERE rnk = 2;

-- Q95: Find the product category with the second highest total sales.
WITH CategorySales AS (
    SELECT p.category, SUM(oi.quantity * oi.unit_price) AS sales,
           RANK() OVER (ORDER BY SUM(oi.quantity * oi.unit_price) DESC) AS rank
    FROM order_items oi
    INNER JOIN products p ON oi.product_id = p.id
    GROUP BY p.category
)
SELECT * FROM CategorySales WHERE rank = 2;

-- Q96: Find the department with the second lowest total salary expense.
WITH DeptSalary AS (
    SELECT department_id, SUM(salary) AS salaries,
           RANK() OVER (ORDER BY SUM(salary) ASC) AS rank
    FROM employees
    GROUP BY department_id
)
SELECT ds.department_id, d.name, ds.salaries
FROM DeptSalary ds
INNER JOIN departments d ON ds.department_id = d.id
WHERE ds.rank = 2;

-- Q97: Find the location with the second highest number of employees.
WITH LocationCount AS (
    SELECT d.location, COUNT(e.id) AS employees_count,
           RANK() OVER (ORDER BY COUNT(e.id) DESC) AS rank
    FROM employees e
    INNER JOIN departments d ON e.department_id = d.id
    GROUP BY d.location
)
SELECT * FROM LocationCount WHERE rank = 2;

-- Q98: Find the manager who has the second highest number of direct reports.
WITH ManagerReports AS (
    SELECT manager_id, COUNT(*) AS reports,
           RANK() OVER (ORDER BY COUNT(*) DESC) AS rank
    FROM employees
    WHERE manager_id IS NOT NULL
    GROUP BY manager_id
)
SELECT mr.manager_id, e.first_name, e.last_name, mr.reports
FROM ManagerReports mr
INNER JOIN employees e ON mr.manager_id = e.id
WHERE mr.rank = 2;

-- Q99: Find the product category with the second lowest stock level.
WITH CategoryStock AS (
    SELECT category, SUM(stock) AS stock_sum,
           RANK() OVER (ORDER BY SUM(stock) ASC) AS rank
    FROM products
    GROUP BY category
)
SELECT * FROM CategoryStock WHERE rank = 2;

-- Q100: Find the customer country with the second highest average order total.
WITH CountryOrders AS (
    SELECT c.country, AVG(o.total_amount) AS avg_amount,
           RANK() OVER (ORDER BY AVG(o.total_amount) DESC) AS rank
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.id
    GROUP BY c.country
)
SELECT * FROM CountryOrders WHERE rank = 2;
