import sys
sys.stdout.reconfigure(encoding='utf-8')
"""
Hashing and Frequency - Practice One Question at a Time
=======================================================
HOW TO USE:
1. Change QUESTION_NUMBER below to the question you want to solve (1 to 100)
2. Write your logic in the corresponding function (q1 to q100)
3. Run the code - it will test only that question
"""

# ==================== CHANGE THIS NUMBER ====================
QUESTION_NUMBER = None  # <-- Change this to solve different questions
# ============================================================


# ==================== ALL 100 QUESTIONS ====================

# --- EASY LEVEL (Q1 - Q25) ---

def q1(nums):
    """Q1: Contains Duplicate. Return True if any value appears at least twice.
    Input: nums = [1, 2, 3, 1]
    Expected Output: True
    """
    seen = set()
    for num in nums:
        if num in seen:
            return True
        seen.add(num)
    return False

def q2(s):
    """Q2: First Unique Character in a String. Return its index (0-indexed) or -1.
    Input: s = "leetcode"
    Expected Output: 0 (index of 'l')
    """
    freq = {}
    for char in s:
        freq[char] = freq.get(char, 0) + 1
    for i, char in enumerate(s):
        if freq[char] == 1:
            return i
    return -1

def q3(s, t):
    """Q3: Valid Anagram. Return True if t is an anagram of s.
    Input: s = "anagram", t = "nagaram"
    Expected: True
    """
    # Write your logic here
    pass

def q4(nums, target):
    """Q4: Two Sum (using Hash Map for O(n) time).
    Input: nums = [2, 7, 11, 15], target = 9
    Expected: [0, 1]
    """
    # Write your logic here
    pass

def q5(nums):
    """Q5: Majority Element. Find element that appears more than n/2 times.
    Input: nums = [3, 2, 3]
    Expected: 3
    """
    # Write your logic here
    pass

def q6(arr):
    """Q6: Unique Number of Occurrences. True if number of occurrences of each value in array is unique.
    Input: arr = [1, 2, 2, 1, 1, 3]
    Expected: True (occurrences: 1->3, 2->2, 3->1. Counts 3, 2, 1 are all unique)
    """
    # Write your logic here
    pass

def q7(pattern, s):
    """Q7: Word Pattern. Check if s follows pattern (e.g. pattern="abba", s="dog cat cat dog").
    Input: pattern = "abba", s = "dog cat cat dog"
    Expected: True
    """
    # Write your logic here
    pass

def q8(s, t):
    """Q8: Isomorphic Strings. Check if s and t can be mapped character-to-character.
    Input: s = "egg", t = "add"
    Expected: True
    """
    # Write your logic here
    pass

def q9(nums1, nums2):
    """Q9: Intersection of Two Arrays (return unique common elements).
    Input: nums1 = [1, 2, 2, 1], nums2 = [2, 2]
    Expected: [2]
    """
    # Write your logic here
    pass

def q10(nums1, nums2):
    """Q10: Intersection of Two Arrays II (retain frequency counts).
    Input: nums1 = [1, 2, 2, 1], nums2 = [2, 2]
    Expected: [2, 2]
    """
    # Write your logic here
    pass

def q11(nums):
    """Q11: Find All Numbers Disappeared in an Array. [1, n] range, some missing.
    Input: nums = [4, 3, 2, 7, 8, 2, 3, 1]
    Expected: [5, 6]
    """
    # Write your logic here
    pass

def q12(nums):
    """Q12: Single Number. Every element appears twice except for one. Find it.
    Input: nums = [4, 1, 2, 1, 2]
    Expected: 4
    """
    # Write your logic here
    pass

def q13(n):
    """Q13: Happy Number. Sum of squares of digits eventually equals 1.
    Input: n = 19
    Expected: True
    """
    # Write your logic here
    pass

def q14(words):
    """Q14: Keyboard Row. Find words that can be typed using letters of only one row of American keyboard.
    Input: words = ["Hello", "Alaska", "Dad", "Peace"]
    Expected: ["Alaska", "Dad"]
    """
    # Write your logic here
    pass

def q15(s, t):
    """Q15: Find the Difference. t is generated by random shuffling s and adding one more letter. Find it.
    Input: s = "abcd", t = "abcde"
    Expected: "e"
    """
    # Write your logic here
    pass

def q16(candies):
    """Q16: Distribute Candies. Max unique candies sister can gain if she gets n/2 candies.
    Input: candies = [1, 1, 2, 2, 3, 3]
    Expected: 3
    """
    # Write your logic here
    pass

def q17(s1, s2):
    """Q17: Uncommon Words from Two Sentences. Word appears exactly once in one sentence, and not in the other.
    Input: s1 = "this apple is sweet", s2 = "this apple is sour"
    Expected: ["sweet", "sour"]
    """
    # Write your logic here
    pass

def q18(words):
    """Q18: Find Common Characters. Find characters common to all strings in words list (including duplicates).
    Input: words = ["bella", "label", "roller"]
    Expected: ["e", "l", "l"]
    """
    # Write your logic here
    pass

def q19(target, arr):
    """Q19: Check if Two Arrays can be made equal by reversing sub-arrays (which implies frequency profiles match).
    Input: target = [1, 2, 3, 4], arr = [2, 4, 1, 3]
    Expected: True
    """
    # Write your logic here
    pass

def q20(s):
    """Q20: Check if All Characters Have Equal Number of Occurrences.
    Input: s = "abacbc"
    Expected: True (a->2, b->2, c->2)
    """
    # Write your logic here
    pass

def q21(paths):
    """Q21: Destination City. Find the city without any outgoing path.
    Input: paths = [["London","New York"],["New York","Lima"],["Lima","Sao Paulo"]]
    Expected: "Sao Paulo"
    """
    # Write your logic here
    pass

def q22(lowLimit, highLimit):
    """Q22: Maximum Number of Balls in a Box. Box number matches sum of digits of ball number.
    Input: lowLimit = 1, highLimit = 10
    Expected: 2 (ball 10 goes to box 1+0=1. box 1 has balls 1, 10. Max is 2 balls)
    """
    # Write your logic here
    pass

def q23(nums):
    """Q23: Sort Array by Increasing Frequency. If frequencies match, sort descending by value.
    Input: nums = [1, 1, 2, 2, 2, 3]
    Expected: [3, 1, 1, 2, 2, 2]
    """
    # Write your logic here
    pass

def q24(path):
    """Q24: Path Crossing. Returns True if path crosses itself on coordinate grid (N, S, E, W).
    Input: path = "NES"
    Expected: False
    """
    # Write your logic here
    pass

def q25(rings):
    """Q25: Rings and Rods. Rods (0-9) that contain all three colors of rings (R, G, B).
    Input: rings = "B0B6G0R6R0R6G9"
    Expected: 1 (rod 0 has R, G, B)
    """
    # Write your logic here
    pass


# --- INTERMEDIATE LEVEL (Q26 - Q60) ---

def q26(strs):
    """Q26: Group Anagrams. Group strings that are anagrams of each other.
    Input: strs = ["eat", "tea", "tan", "ate", "nat", "bat"]
    Expected: [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]] (sorted for testing)
    """
    # Write your logic here
    pass

def q27(nums, k):
    """Q27: Top K Frequent Elements. Return the k most frequent elements in any order.
    Input: nums = [1, 1, 1, 2, 2, 3], k = 2
    Expected: [1, 2]
    """
    # Write your logic here
    pass

def q28(words, k):
    """Q28: Top K Frequent Words. Return sorted alphabetically if frequencies match.
    Input: words = ["i", "love", "leetcode", "i", "love", "coding"], k = 2
    Expected: ["i", "love"]
    """
    # Write your logic here
    pass

def q29(nums, k):
    """Q29: Subarray Sum Equals K. Return total number of subarrays whose sum equals k.
    Input: nums = [1, 1, 1], k = 2
    Expected: 2
    """
    # Write your logic here
    pass

def q30(nums):
    """Q30: Longest Consecutive Sequence. Length of longest consecutive elements sequence in O(n).
    Input: nums = [100, 4, 200, 1, 3, 2]
    Expected: 4 ([1, 2, 3, 4])
    """
    # Write your logic here
    pass

def q31(s):
    """Q31: Sort Characters By Frequency. Decreasing order.
    Input: s = "tree"
    Expected: "eert" (or "eetr")
    """
    # Write your logic here
    pass

def q32(s, order):
    """Q32: Custom Sort String. Permute s to match custom sorting order.
    Input: s = "abcd", order = "cba"
    Expected: "cbad" (or similar maintaining order)
    """
    # Write your logic here
    pass

def q33(nums):
    """Q33: Find All Duplicates in an Array. Elements appear once or twice.
    Input: nums = [4, 3, 2, 7, 8, 2, 3, 1]
    Expected: [2, 3]
    """
    # Write your logic here
    pass

def q34(board):
    """Q34: Valid Sudoku.
    Input: board = 9x9 sudoku state
    Expected: True
    """
    # Write your logic here
    pass

def q35(nums, k):
    """Q35: Continuous Subarray Sum (sum is multiple of k, length >= 2).
    Input: nums = [23, 2, 4, 6, 7], k = 6
    Expected: True
    """
    # Write your logic here
    pass

def q36(nums, k):
    """Q36: Subarray Sums Divisible by K.
    Input: nums = [4, 5, 0, -2, -3, 1], k = 5
    Expected: 7
    """
    # Write your logic here
    pass

def q37(nums):
    """Q37: Array of Doubled Pairs. Can reorder to form pairs where arr[2*i+1] = 2 * arr[2*i].
    Input: nums = [4, -2, 2, -4]
    Expected: True (pairs: (-2, -4) and (2, 4))
    """
    # Write your logic here
    pass

def q38(tasks, n):
    """Q38: Task Scheduler. Find least units of time to finish all tasks with cooldown n.
    Input: tasks = ["A","A","A","B","B","B"], n = 2
    Expected: 8 (A -> B -> idle -> A -> B -> idle -> A -> B)
    """
    # Write your logic here
    pass

def q39(arr):
    """Q39: Check If Array Pairs Are Divisible by k. Can group array into pairs whose sums divisible by k.
    Input: arr = ([1, 2, 3, 4, 5, 10, 6, 7, 8, 9], 5)
    Expected: True
    """
    # Write your logic here
    pass

def q40(nums):
    """Q40: Find players with zero or one losses (returns list of [undefeated, 1-loss]).
    Input: nums = [[1,3],[2,3],[3,6],[5,6],[5,7],[4,5],[4,8],[4,9],[10,4],[10,9]]
    Expected: [[1, 2, 10], [4, 5, 7, 8]]
    """
    # Write your logic here
    pass

def q41(s):
    """Q41: Minimum Deletions to Make Character Frequencies Unique.
    Input: s = "aab"
    Expected: 0
    """
    # Write your logic here
    pass

def q42(nums, target):
    """Q42: Count Subarrays Where Max Element Appears at Least K Times.
    Input: nums = ([1, 3, 2, 3, 3], 2)
    Expected: 6
    """
    # Write your logic here
    pass

def q43(s):
    """Q43: Max Length of a Concatenated String with Unique Characters.
    Input: s = ["un", "iq", "ue"]
    Expected: 4 ("uniq" or "ique")
    """
    # Write your logic here
    pass

def q44(nums):
    """Q44: Split Array into Consecutive Subsequences.
    Input: nums = [1, 2, 3, 3, 4, 5]
    Expected: True
    """
    # Write your logic here
    pass

def q45(nums, target):
    """Q45: Count Number of Pairs With Absolute Difference K.
    Input: nums = ([1, 2, 2, 1], 1)
    Expected: 4
    """
    # Write your logic here
    pass

def q46(s):
    """Q46: Number of Good Ways to Split a String (equal unique chars in left/right).
    Input: s = "aacaba"
    Expected: 2
    """
    # Write your logic here
    pass

def q47(nums):
    """Q47: Sum of Beauty of All Substrings.
    Input: nums = "aabcb"
    Expected: 5
    """
    # Write your logic here
    pass

def q48(nums):
    """Q48: Least Number of Unique Integers after K Removals.
    Input: nums = ([5, 5, 4], 1)
    Expected: 1
    """
    # Write your logic here
    pass

def q49(s):
    """Q49: Partition Labels.
    Input: s = "ababcbacadefegdehijhklij"
    Expected: [9, 7, 8]
    """
    # Write your logic here
    pass

def q50(arr):
    """Q50: Reduce Array Size to The Half (min set of elements to delete to shrink size >= half).
    Input: arr = [3, 3, 3, 3, 5, 5, 5, 2, 2, 7]
    Expected: 2 (delete 3s and 5s)
    """
    # Write your logic here
    pass

def q51(nums, target):
    """Q51: Number of Subarrays with Bounded Maximum.
    Input: nums = ([2, 1, 4, 3], 2, 3)
    Expected: 3
    """
    # Write your logic here
    pass

def q52(nums, target):
    """Q52: Subarray Sums Divisible by K.
    Input: nums = ([4, 5, 0, -2, -3, 1], 5)
    Expected: 7
    """
    # Write your logic here
    pass

def q53(arr):
    """Q53: Longest Mountain in Array.
    Input: arr = [2, 1, 4, 7, 3, 2, 5]
    Expected: 5
    """
    # Write your logic here
    pass

def q54(heights):
    """Q54: Trapping Rain Water (sliding window / two pointer).
    Input: heights = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]
    Expected: 6
    """
    # Write your logic here
    pass

def q55(nums, k):
    """Q55: Count Subarrays with Median K.
    Input: nums = ([3, 2, 1, 4, 5], 4)
    Expected: 3
    """
    # Write your logic here
    pass

def q56(nums):
    """Q56: Maximum Product Subarray.
    Input: nums = [2, 3, -2, 4]
    Expected: 6
    """
    # Write your logic here
    pass

def q57(nums, k):
    """Q57: Maximum Subarray Sum with One Deletion.
    Input: nums = [1, -2, 0, 3]
    Expected: 4
    """
    # Write your logic here
    pass

def q58(nums):
    """Q58: Maximum Absolute Sum of Any Subarray.
    Input: nums = [1, -3, 2, 3, -4]
    Expected: 5
    """
    # Write your logic here
    pass

def q59(arr):
    """Q59: Subarray Product Less than K with Negatives.
    Input: arr = ([10, 5, 2, 6], 100)
    Expected: 8
    """
    # Write your logic here
    pass

def q60(s):
    """Q60: Longest Substring of All Vowels in Order.
    Input: s = "aeiaaioooaaeiouuu"
    Expected: 7
    """
    # Write your logic here
    pass


# --- ADVANCED LEVEL (Q61 - Q100) ---

def q61(nums, k):
    """Q61: Minimum Swaps to Group All 1's Together.
    Input: nums = [1, 0, 1, 0, 1]
    Expected: 1
    """
    # Write your logic here
    pass

def q62(s):
    """Q62: Longest Substring with At Least K Unique Vowels.
    Input: s = ("leetcode", 2)
    Expected: 8
    """
    # Write your logic here
    pass

def q63(nums, k):
    """Q63: Find All Unique Subarrays of Size K.
    Input: nums = ([1, 2, 1, 2, 1, 3], 3)
    Expected: 3
    """
    # Write your logic here
    pass

def q64(n, edges):
    """Q64: Sliding Window on Graph.
    Input: n = (5, [[1, 2, 10], [2, 3, 20], [3, 4, 30]])
    Expected: 60
    """
    # Write your logic here
    pass

def q65(nums, target):
    """Q65: Longest Subarray with Sum Equal to Target.
    Input: nums = ([1, -1, 5, -2, 3], 3)
    Expected: 4
    """
    # Write your logic here
    pass

def q66(nums, k):
    """Q66: Max Sum of Subarray of Size K with No Duplicates.
    Input: nums = ([1, 5, 4, 2, 9, 9, 9], 3)
    Expected: 15
    """
    # Write your logic here
    pass

def q67(nums):
    """Q67: Find Minimum of All Subarrays of Size K.
    Input: nums = ([2, 1, 3, 4, 6, 3, 8])
    Expected: [1, 1, 3, 3, 3]
    """
    # Write your logic here
    pass

def q68(nums, target):
    """Q68: Count Subarrays with Sum Less Than Target.
    Input: nums = ([2, 1, 4, 3], 5)
    Expected: 4
    """
    # Write your logic here
    pass

def q69(nums):
    """Q69: Maximum Difference in a Subarray of Size K.
    Input: nums = ([1, 3, 6, 1, 9, 2])
    Expected: 8
    """
    # Write your logic here
    pass

def q70(nums, k):
    """Q70: Number of Subarrays with Product Less than K.
    Input: nums = ([10, 5, 2, 6], 100)
    Expected: 8
    """
    # Write your logic here
    pass

def q71(nums):
    """Q71: Find Longest Alternating Subarray.
    Input: nums = [1, 0, 1, 0, 1, 1, 0]
    Expected: 5
    """
    # Write your logic here
    pass

def q72(s):
    """Q72: Find Longest Substring containing even counts of vowels.
    Input: s = "eleetminicoworoep"
    Expected: 13
    """
    # Write your logic here
    pass

def q73(nums, k):
    """Q73: K-Sum Subarrays.
    Input: nums = ([1, 2, 3], 3)
    Expected: 2
    """
    # Write your logic here
    pass

def q74(s):
    """Q74: Longest Chunked Palindrome Decomposition.
    Input: s = "ghiabcdefhelloadamhelloabcdefghi"
    Expected: 7
    """
    # Write your logic here
    pass

def q75(s, t):
    """Q75: Distinct Subsequences.
    Input: s = "rabbbit", t = "rabbit"
    Expected: 3
    """
    # Write your logic here
    pass

def q76(lists):
    """Q76: Merge K Sorted Lists.
    Input: lists = [[1, 4, 5], [1, 3, 4], [2, 6]]
    Expected: [1, 1, 2, 3, 4, 4, 5, 6]
    """
    # Write your logic here
    pass

def q77(arr):
    """Q77: Shortest Subarray to be Removed to Make Array Sorted.
    Input: arr = [1, 2, 3, 10, 4, 2, 3, 5]
    Expected: 3
    """
    # Write your logic here
    pass

def q78(start, end):
    """Q78: Swap Adjacent in LR String.
    Input: start = "RXXLRXRXL", end = "XRLXXRRLX"
    Expected: True
    """
    # Write your logic here
    pass

def q79(s):
    """Q79: Remove Duplicate Letters.
    Input: s = "bcabc"
    Expected: "abc"
    """
    # Write your logic here
    pass

def q80(nums, k):
    """Q80: Maximum Score of a Good Subarray.
    Input: nums = ([1, 4, 3, 7, 4, 5], 3)
    Expected: 15
    """
    # Write your logic here
    pass

def q81(nums, k):
    """Q81: Subarray Sums Divisible by K.
    Input: nums = [4, 5, 0, -2, -3, 1], k = 5
    Expected: 7
    """
    # Write your logic here
    pass

def q82(s):
    """Q82: Optimal Partition of String.
    Input: s = "abacaba"
    Expected: 4
    """
    # Write your logic here
    pass

def q83(nums, k):
    """Q83: Count Subarrays With Median K.
    Input: nums = ([3, 2, 1, 4, 5], 4)
    Expected: 3
    """
    # Write your logic here
    pass

def q84(fruits):
    """Q84: Fruit Into Baskets.
    Input: fruits = [1, 2, 3, 2, 2]
    Expected: 4
    """
    # Write your logic here
    pass

def q85(nums):
    """Q85: Minimum Operations to Make Array Continuous.
    Input: nums = [4, 2, 5, 3]
    Expected: 0
    """
    # Write your logic here
    pass

def q86(s):
    """Q86: Replace the Substring for Balanced String.
    Input: s = "QWER"
    Expected: 0
    """
    # Write your logic here
    pass

def q87(nums, k):
    """Q87: Constrained Subsequence Sum.
    Input: nums = [10, 2, -10, 5, 20], k = 2
    Expected: 37
    """
    # Write your logic here
    pass

def q88(nums, limit):
    """Q88: Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit.
    Input: nums = [8, 2, 4, 7], limit = 4
    Expected: 2
    """
    # Write your logic here
    pass

def q89(nums, k):
    """Q89: Count Subarrays Where Max Element Appears at Least K Times.
    Input: nums = ([1, 3, 2, 3, 3], 2)
    Expected: 6
    """
    # Write your logic here
    pass

def q90(s):
    """Q90: Minimum Number of Flips to Make the Binary String Alternating.
    Input: s = "111000"
    Expected: 2
    """
    # Write your logic here
    pass

def q91(nums, k):
    """Q91: Split Array Largest Sum.
    Input: nums = [7, 2, 5, 10, 8], k = 2
    Expected: 18
    """
    # Write your logic here
    pass

def q92(weights, days):
    """Q92: Capacity To Ship Packages Within D Days.
    Input: weights = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], days = 5
    Expected: 15
    """
    # Write your logic here
    pass

def q93(piles, h):
    """Q93: Koko Eating Bananas.
    Input: piles = [3, 6, 7, 11], h = 8
    Expected: 4
    """
    # Write your logic here
    pass

def q94(nums, queries):
    """Q94: Minimum Absolute Difference Query.
    Input: nums = ([1, 3, 4, 8], [[0, 1], [1, 2], [2, 3], [0, 3]])
    Expected: [2, 1, 4, 1]
    """
    # Write your logic here
    pass

def q95(head, k):
    """Q95: Reverse Nodes in k-Group.
    Input: head = [1, 2, 3, 4, 5], k = 2
    Expected: [2, 1, 4, 3, 5]
    """
    # Write your logic here
    pass

def q96(head):
    """Q96: Sort List.
    Input: head = [4, 2, 1, 3]
    Expected: [1, 2, 3, 4]
    """
    # Write your logic here
    pass

def q97(head, x):
    """Q97: Partition List.
    Input: head = ([1, 4, 3, 2, 5, 2], 3)
    Expected: [1, 2, 2, 4, 3, 5]
    """
    # Write your logic here
    pass

def q98(head):
    """Q98: Palindrome Linked List.
    Input: head = [1, 2, 2, 1]
    Expected: True
    """
    # Write your logic here
    pass

def q99(head):
    """Q99: Linked List Cycle II.
    Input: head = ([3, 2, 0, -4], 1)
    Expected: 1
    """
    # Write your logic here
    pass

def q100(nums):
    """Q100: Find the Duplicate Number.
    Input: nums = [1, 3, 4, 2, 2]
    Expected: 2
    """
    # Write your logic here
    pass


# ==================== TEST SUITE DICTIONARY ====================

TESTS = {
    1: {'func': q1, 'args': [[1, 2, 3, 1]], 'expected': True},
    2: {'func': q2, 'args': ["leetcode"], 'expected': 0},
    3: {'func': q3, 'args': ["anagram", "nagaram"], 'expected': True},
    4: {'func': q4, 'args': [[2, 7, 11, 15], 9], 'expected': [0, 1]},
    5: {'func': q5, 'args': [[3, 2, 3]], 'expected': 3},
    6: {'func': q6, 'args': [[1, 2, 2, 1, 1, 3]], 'expected': True},
    7: {'func': q7, 'args': ["abba", "dog cat cat dog"], 'expected': True},
    8: {'func': q8, 'args': ["egg", "add"], 'expected': True},
    9: {'func': q9, 'args': [[1, 2, 2, 1], [2, 2]], 'expected': [2]},
    10: {'func': q10, 'args': [[1, 2, 2, 1], [2, 2]], 'expected': [2, 2]},
    11: {'func': q11, 'args': [[4, 3, 2, 7, 8, 2, 3, 1]], 'expected': [5, 6]},
    12: {'func': q12, 'args': [[4, 1, 2, 1, 2]], 'expected': 4},
    13: {'func': q13, 'args': [19], 'expected': True},
    14: {'func': q14, 'args': [["Hello", "Alaska", "Dad", "Peace"]], 'expected': ["Alaska", "Dad"]},
    15: {'func': q15, 'args': ["abcd", "abcde"], 'expected': "e"},
    16: {'func': q16, 'args': [[1, 1, 2, 2, 3, 3]], 'expected': 3},
    17: {'func': q17, 'args': ["this apple is sweet", "this apple is sour"], 'expected': ["sweet", "sour"]},
    18: {'func': q18, 'args': [["bella", "label", "roller"]], 'expected': ["e", "l", "l"]},
    19: {'func': q19, 'args': [[1, 2, 3, 4], [2, 4, 1, 3]], 'expected': True},
    20: {'func': q20, 'args': ["abacbc"], 'expected': True},
    21: {'func': q21, 'args': [[["London", "New York"], ["New York", "Lima"], ["Lima", "Sao Paulo"]]], 'expected': "Sao Paulo"},
    22: {'func': q22, 'args': [1, 10], 'expected': 2},
    23: {'func': q23, 'args': [[1, 1, 2, 2, 2, 3]], 'expected': [3, 1, 1, 2, 2, 2]},
    24: {'func': q24, 'args': ["NES"], 'expected': False},
    25: {'func': q25, 'args': ["B0B6G0R6R0R6G9"], 'expected': 1},
    
    26: {'func': q26, 'args': [["eat", "tea", "tan", "ate", "nat", "bat"]], 'expected': [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]]},
    27: {'func': q27, 'args': [[1, 1, 1, 2, 2, 3], 2], 'expected': [1, 2]},
    28: {'func': q28, 'args': [["i", "love", "leetcode", "i", "love", "coding"], 2], 'expected': ["i", "love"]},
    29: {'func': q29, 'args': [[1, 1, 1], 2], 'expected': 2},
    30: {'func': q30, 'args': [[100, 4, 200, 1, 3, 2]], 'expected': 4},
    31: {'func': q31, 'args': ["tree"], 'expected': "eert"},
    32: {'func': q32, 'args': ["abcd", "cba"], 'expected': "cbad"},
    33: {'func': q33, 'args': [[4, 3, 2, 7, 8, 2, 3, 1]], 'expected': [2, 3]},
    34: {'func': q34, 'args': [[]], 'expected': True},
    35: {'func': q35, 'args': [[23, 2, 4, 6, 7], 6], 'expected': True},
    36: {'func': q36, 'args': [[4, 5, 0, -2, -3, 1], 5], 'expected': 7},
    37: {'func': q37, 'args': [[4, -2, 2, -4]], 'expected': True},
    38: {'func': q38, 'args': [["A", "A", "A", "B", "B", "B"], 2], 'expected': 8},
    39: {'func': q39, 'args': [[1, 2, 3, 4, 5, 10, 6, 7, 8, 9], 5], 'expected': True},
    40: {'func': q40, 'args': [[[1, 3], [2, 3], [3, 6], [5, 6], [5, 7], [4, 5], [4, 8], [4, 9], [10, 4], [10, 9]]], 'expected': [[1, 2, 10], [4, 5, 7, 8]]},
    41: {'func': q41, 'args': ["aab"], 'expected': 0},
    42: {'func': q42, 'args': [[1, 3, 2, 3, 3], 2], 'expected': 6},
    43: {'func': q43, 'args': [["un", "iq", "ue"]], 'expected': 4},
    44: {'func': q44, 'args': [[1, 2, 3, 3, 4, 5]], 'expected': True},
    45: {'func': q45, 'args': [[1, 2, 2, 1], 1], 'expected': 4},
    46: {'func': q46, 'args': ["aacaba"], 'expected': 2},
    47: {'func': q47, 'args': ["aabcb"], 'expected': 5},
    48: {'func': q48, 'args': [[5, 5, 4], 1], 'expected': 1},
    49: {'func': q49, 'args': ["ababcbacadefegdehijhklij"], 'expected': [9, 7, 8]},
    50: {'func': q50, 'args': [[3, 3, 3, 3, 5, 5, 5, 2, 2, 7]], 'expected': 2},
    51: {'func': q51, 'args': [[2, 1, 4, 3], 2, 3], 'expected': 3},
    52: {'func': q52, 'args': [[4, 5, 0, -2, -3, 1], 5], 'expected': 7},
    53: {'func': q53, 'args': [[2, 1, 4, 7, 3, 2, 5]], 'expected': 5},
    54: {'func': q54, 'args': [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], 'expected': 6},
    55: {'func': q55, 'args': [[3, 2, 1, 4, 5], 4], 'expected': 3},
    56: {'func': q56, 'args': [[2, 3, -2, 4]], 'expected': 6},
    57: {'func': q57, 'args': [[1, -2, 0, 3]], 'expected': 4},
    58: {'func': q58, 'args': [[1, -3, 2, 3, -4]], 'expected': 5},
    59: {'func': q59, 'args': [[10, 5, 2, 6], 100], 'expected': 8},
    60: {'func': q60, 'args': ["aeiaaioooaaeiouuu"], 'expected': 7},
    
    61: {'func': q61, 'args': [[1, 0, 1, 0, 1], 2], 'expected': 1},
    62: {'func': q62, 'args': ["leetcode", 2], 'expected': 8},
    63: {'func': q63, 'args': [[1, 2, 1, 2, 1, 3], 3], 'expected': 3},
    64: {'func': q64, 'args': [5, [[1, 2, 10], [2, 3, 20], [3, 4, 30]]], 'expected': 60},
    65: {'func': q65, 'args': [[1, -1, 5, -2, 3], 3], 'expected': 4},
    66: {'func': q66, 'args': [[1, 5, 4, 2, 9, 9, 9], 3], 'expected': 15},
    67: {'func': q67, 'args': [[2, 1, 3, 4, 6, 3, 8]], 'expected': [1, 1, 3, 3, 3]},
    68: {'func': q68, 'args': [[2, 1, 4, 3], 5], 'expected': 4},
    69: {'func': q69, 'args': [[1, 3, 6, 1, 9, 2]], 'expected': 8},
    70: {'func': q70, 'args': [[10, 5, 2, 6], 100], 'expected': 8},
    71: {'func': q71, 'args': [[1, 0, 1, 0, 1, 1, 0]], 'expected': 5},
    72: {'func': q72, 'args': ["eleetminicoworoep"], 'expected': 13},
    73: {'func': q73, 'args': [[1, 2, 3], 3], 'expected': 2},
    74: {'func': q74, 'args': ["ghiabcdefhelloadamhelloabcdefghi"], 'expected': 7},
    75: {'func': q75, 'args': ["rabbbit", "rabbit"], 'expected': 3},
    76: {'func': q76, 'args': [[[1, 4, 5], [1, 3, 4], [2, 6]]], 'expected': [1, 1, 2, 3, 4, 4, 5, 6]},
    77: {'func': q77, 'args': [[1, 2, 3, 10, 4, 2, 3, 5]], 'expected': 3},
    78: {'func': q78, 'args': ["RXXLRXRXL", "XRLXXRRLX"], 'expected': True},
    79: {'func': q79, 'args': ["bcabc"], 'expected': "abc"},
    80: {'func': q80, 'args': [[1, 4, 3, 7, 4, 5], 3], 'expected': 15},
    81: {'func': q81, 'args': [[4, 5, 0, -2, -3, 1], 5], 'expected': 7},
    82: {'func': q82, 'args': ["abacaba"], 'expected': 4},
    83: {'func': q83, 'args': [[3, 2, 1, 4, 5], 4], 'expected': 3},
    84: {'func': q84, 'args': [[1, 2, 3, 2, 2]], 'expected': 4},
    85: {'func': q85, 'args': [[4, 2, 5, 3]], 'expected': 0},
    86: {'func': q86, 'args': ["QWER"], 'expected': 0},
    87: {'func': q87, 'args': [[10, 2, -10, 5, 20], 2], 'expected': 37},
    88: {'func': q88, 'args': [[8, 2, 4, 7], 4], 'expected': 2},
    89: {'func': q89, 'args': [[1, 3, 2, 3, 3], 2], 'expected': 6},
    90: {'func': q90, 'args': ["111000"], 'expected': 2},
    91: {'func': q91, 'args': [[7, 2, 5, 10, 8], 2], 'expected': 18},
    92: {'func': q92, 'args': [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5], 'expected': 15},
    93: {'func': q93, 'args': [[3, 6, 7, 11], 8], 'expected': 4},
    94: {'func': q94, 'args': [[1, 3, 4, 8], [[0, 1], [1, 2], [2, 3], [0, 3]]], 'expected': [2, 1, 4, 1]},
    95: {'func': q95, 'args': [[1, 2, 3, 4, 5], 2], 'expected': [2, 1, 4, 3, 5]},
    96: {'func': q96, 'args': [[4, 2, 1, 3]], 'expected': [1, 2, 3, 4]},
    97: {'func': q97, 'args': [[1, 4, 3, 2, 5, 2], 3], 'expected': [1, 2, 2, 4, 3, 5]},
    98: {'func': q98, 'args': [[1, 2, 2, 1]], 'expected': True},
    99: {'func': q99, 'args': [[3, 2, 0, -4], 1], 'expected': 1},
    100: {'func': q100, 'args': [[1, 3, 4, 2, 2]], 'expected': 2},
}


# ==================== RUN TEST ====================

def run_test(QUESTION_NUMBER, silent=False):
    import io
    import sys
    
    old_stdout = sys.stdout
    captured = io.StringIO()
    if silent:
        sys.stdout = captured
        
    try:
        test = TESTS.get(QUESTION_NUMBER)
        if not test:
            if not silent:
                print(f"❌ Question {QUESTION_NUMBER} not found!")
            return False
            
        func = test['func']
        args = test['args']
        expected = test['expected']
        
        if not silent:
            print(f"\n{'='*60}")
            print(f"Question {QUESTION_NUMBER}: {func.__doc__.splitlines()[0] if func.__doc__ else 'No docstring'}")
            print(f"{'='*60}")
            print(f"Input: {args}")
            print(f"Expected: {expected}")
            print("-" * 60)
            
        # Run conversion logic if applicable (Linked Lists / Trees)
        # We check filename to apply custom converters if they are defined
        import os
        filename = os.path.basename(__file__)
        
        if filename == "linked_lists.py" and QUESTION_NUMBER <= 25 and QUESTION_NUMBER != 19:
            processed_args = []
            if QUESTION_NUMBER == 2:
                list_vals = args[0]
                target_val = args[1]
                head = to_linked_list(list_vals)
                curr = head
                target_node = None
                while curr:
                    if curr.val == target_val:
                        target_node = curr
                        break
                    curr = curr.next
                func(target_node)
                result = to_list(head)
            elif QUESTION_NUMBER == 8:
                list_vals = args[0]
                cycle_pos = args[1]
                head = to_linked_list(list_vals)
                if cycle_pos != -1:
                    curr = head
                    cycle_node = None
                    tail = None
                    idx = 0
                    while curr:
                        if idx == cycle_pos:
                            cycle_node = curr
                        tail = curr
                        curr = curr.next
                        idx += 1
                    if tail and cycle_node:
                        tail.next = cycle_node
                result = func(head)
            elif QUESTION_NUMBER == 9:
                listA = args[0]
                listB = args[1]
                skipA = args[2]
                skipB = args[3]
                headA = to_linked_list(listA[:skipA])
                headB = to_linked_list(listB[:skipB])
                intersect = to_linked_list(listA[skipA:])
                if headA:
                    curr = headA
                    while curr.next:
                        curr = curr.next
                    curr.next = intersect
                else:
                    headA = intersect
                if headB:
                    curr = headB
                    while curr.next:
                        curr = curr.next
                    curr.next = intersect
                else:
                    headB = intersect
                res_node = func(headA, headB)
                result = to_list(res_node)
            elif QUESTION_NUMBER == 23:
                list_nodes = [to_linked_list(arr) for arr in args[0]]
                res_node = func(list_nodes)
                result = to_list(res_node)
            elif QUESTION_NUMBER == 25:
                list_vals = args[0]
                cycle_pos = args[1]
                head = to_linked_list(list_vals)
                if cycle_pos != -1:
                    curr = head
                    cycle_node = None
                    tail = None
                    idx = 0
                    while curr:
                        if idx == cycle_pos:
                            cycle_node = curr
                        tail = curr
                        curr = curr.next
                        idx += 1
                    if tail and cycle_node:
                        tail.next = cycle_node
                res_node = func(head)
                if not res_node:
                    result = -1
                else:
                    curr = head
                    idx = 0
                    result = -1
                    for _ in range(100):
                        if curr == res_node:
                            result = idx
                            break
                        curr = curr.next
                        idx += 1
            else:
                for arg in args:
                    if isinstance(arg, list):
                        processed_args.append(to_linked_list(arg))
                    else:
                        processed_args.append(arg)
                res_node = func(*processed_args) if len(processed_args) > 1 else func(processed_args[0])
                result = to_list(res_node) if isinstance(res_node, ListNode) else res_node
                
        elif filename == "trees_and_bst.py" and QUESTION_NUMBER <= 25:
            processed_args = []
            for arg in args:
                if isinstance(arg, list):
                    processed_args.append(to_tree(arg))
                else:
                    processed_args.append(arg)
            res_val = func(*processed_args) if len(processed_args) > 1 else func(processed_args[0])
            if isinstance(res_val, TreeNode):
                result = to_list(res_val)
            else:
                result = res_val
                
        elif filename == "tries.py":
            # Tries test runner class-based instantiation and method calling
            commands = args[0]
            arguments = args[1]
            obj = func() # Instantiate the class (Trie or MapSum)
            result = [None]
            for i in range(1, len(commands)):
                cmd = commands[i]
                arg = arguments[i]
                method = getattr(obj, cmd)
                res = method(*arg) if arg else method()
                result.append(res)
                
        else:
            # Standard input/output check
            result = func(*args) if isinstance(args, list) else func(args)
            
        # Custom result sorting for combinations/subsets/permutations
        if filename == "backtracking.py" and QUESTION_NUMBER in [1, 2, 4, 13, 20]:
            if result and isinstance(result, list):
                result = sorted([sorted(x) if isinstance(x, list) else x for x in result])
                expected = sorted([sorted(x) if isinstance(x, list) else x for x in expected])
        elif filename == "bit_manipulation.py" and QUESTION_NUMBER in [9, 11]:
            if result and isinstance(result, list):
                result = sorted([sorted(x) if isinstance(x, list) else x for x in result])
                expected = sorted([sorted(x) if isinstance(x, list) else x for x in expected])
        elif filename == "loop_basics.py" and QUESTION_NUMBER in [41]:
            if result and isinstance(result, list):
                result = sorted([sorted(x) if isinstance(x, list) else x for x in result])
                expected = sorted([sorted(x) if isinstance(x, list) else x for x in expected])
                
        if not silent:
            print(f"Your Output: {result}")
            
        if result == expected:
            if not silent:
                print("\n✅ PASS - Correct!")
            return True
        else:
            if not silent:
                print("\n❌ FAIL - Output doesn't match expected")
            return False
            
    except Exception as e:
        if not silent:
            print(f"\n❌ ERROR: {e}")
        return False
    finally:
        sys.stdout = old_stdout

if __name__ == "__main__":
    import sys
    # Check CLI arguments first
    if len(sys.argv) > 1:
        try:
            QUESTION_NUMBER = int(sys.argv[1])
        except ValueError:
            pass

    # If QUESTION_NUMBER is None or 0, auto-detect the highest-numbered non-empty question
    if QUESTION_NUMBER is None or QUESTION_NUMBER == 0:
        import ast
        import inspect
        
        detected_q = 1
        for q_num in sorted(TESTS.keys(), reverse=True):
            test = TESTS[q_num]
            func = test['func']
            try:
                source = inspect.getsource(func)
                tree = ast.parse(source)
                func_def = tree.body[0]
                body = func_def.body
                
                # Check if there are non-docstring, non-pass statements
                non_empty = False
                for stmt in body:
                    # Ignore docstrings
                    if isinstance(stmt, ast.Expr) and isinstance(stmt.value, (ast.Constant, ast.Str)):
                        continue
                    # Ignore pass
                    if isinstance(stmt, ast.Pass):
                        continue
                    non_empty = True
                    break
                
                if non_empty:
                    detected_q = q_num
                    break
            except Exception:
                pass
        QUESTION_NUMBER = detected_q

    # Run the selected question in verbose mode
    run_test(QUESTION_NUMBER, silent=False)
